### ISSUE TITLE
Unable to withdraw from competition as co-pilot

### ISSUE THREAD

**Issue by olvesh** [airsports-no/airsportslivetracking#18]
If I am added to a contest as a co-pilot I am unable to withdraw and setup a new team. This is problematic in e.g. club training contests where you mix and match teams over time.

Maybe there is a simpler solution, but it is not apparent in the UI

**Comment by kolaf** [comment]
This is by design. Self registration of teams enforces that the team is "owned" by the pilot. Administrator management allows a person to be member of multiple teams, but this is not supported for self registration. Enabling this introduces a new challenge in matching which registration is to be managed by the user.
